import { Inter } from "next/font/google";
import "./globals.css";
// import "react-quill/dist/quill.bubble.css";
import "react-quill/dist/quill.snow.css";
import { SignedIn, ClerkProvider, SignedOut, SignIn, UserButton } from "@clerk/nextjs";
import { Toaster } from "@/Components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-white">
          <header className="flex justify-between p-4">
            <h1 className="text-black">Tech Journal</h1>
            <UserButton showName />
          </header>
          <section className="flex item-center justify-center h-screen">
            <SignedOut>
              <SignIn routing="hash" />
            </SignedOut>
            <SignedIn>
              {children}
              <Toaster />
            </SignedIn>
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
